### ISSUE TITLE
Connected three  or more of keyboards at the same time?

### ISSUE THREAD

**Issue by YCF** [reversebias/mitosis#2]
how about a numpad ?

**Comment by reversebias** [comment]
There's nothing that would prevent this working, except the gazell limit of 8. Do you mean a 3rd mitosis keyboard half? or a new hardware design in the shape of a numpad?

**Comment by YCF** [comment]
Oh,yes!

I menu a 3rd mitosis keyboard half that in the shape of a numpad.
