### ISSUE TITLE
can you please provide some test firmware?

### ISSUE THREAD

**Issue by YCF** [reversebias/mitosis#3]
First of all, thank you very much for the design.
At present I was in trouble, I have welded the receiver and keyboard, it does not work properly. The two modules and the pro micro  I have flashed.

But,because the PCB does not some indicate working status leds, so we do not know whether the wireless module is working properly.
I hope you can provide some basic wireless test firmware, I can think of is:

1. Receiver Test firmware:
After the power is on, send a button keep pressing and releasing to Pro micro , so we can know that the receiver module is working properly.

2. Keyboard Test firmware:
Send the letter 'A'( S6 ?) to the receiver repeat, so we can know that the wireless part of the receiver and keyboard is working properly.

Now I am facing a non-working mitosis, and I totally do not know how to fix it.  

T_T

**Comment by YCF** [comment]
Maybe a blink firework? At the keyboard  part every mx switch is an io,so we can connect a led to the mx switch foot to test it.

**Comment by reversebias** [comment]
This is a really great idea. Pester me if it's not up by next weekend. :)

**Comment by YCF** [comment]
https://youtu.be/kEVsoy24RTQ
My dirty code...Check the core51852 is working,and the lines is good.
Wish it can help.

**Comment by TyberiusPrime** [comment]
any chance you can publish that 'blinky' sketch, YFC?

**Comment by YCF** [comment]
@TyberiusPrime 
Here is the hex files:
[mitosis_let_test.zip](https://github.com/reversebias/mitosis/files/1100231/mitosis_let_test.zip)

I modified the mitosis PCB, so some led position may be different, but each led should be bright.

**Comment by joric** [comment]
@YCF do they need resistors? Could you please also build something to test receiver and its module, because I'm not getting any response from it and keyboard doesn't work, and I have no idea why.

**Comment by codeincontext** [comment]
EDIT: This is now fixed. I had a floating RX pin on the pro micro

I'm having similar issues to @joric's post. All chips are programming ok but the keyboard as a whole isn't working. I've no idea how to debug it with OpenOCD so it's a total black box to me

I'd appreciate advice on how to:
- Get log messages from the chip
- Simulate keypresses on the receiver

Thanks

**Comment by codeincontext** [comment]
I just realised this issue is closed so people wouldn't have got notifications

Pinging @YCF @reversebias @joric (hope that's not spammy)

**Comment by joric** [comment]
Hey man! I managed to solve it with #7. You can also browse https://github.com/joric/mitosis/tree/devel there are precompiled binaries I used.
