### ISSUE TITLE
nRF SDK 11 link is wrong

### ISSUE THREAD

**Issue by joric** [reversebias/mitosis#5]
For SDK 11 I'd rather point here: https://developer.nordicsemi.com/nRF5_SDK/ than here as in your readme: https://www.nordicsemi.com/eng/nordic/Products/nRF5-SDK/nRF5-SDK-v12-zip/54291
There are no links to the previous versions and SDK 12 is not compatible with current sources:
`fatal error: core_cm0.h: No such file or directory #include "core_cm0.h"`

P.S. A teeny tiny suggestion - could you please upload your precompiled QMK firmware too and make sure it all works together? It'd make things much easier for beginners. Apparently [I'm not the only one](https://github.com/reversebias/mitosis/issues/3) who can't make the receiver work. Thanks!

Upd: finally made your firmware compatible with my nrf51822 module (YJ-14015): https://github.com/reversebias/mitosis/pull/7

**Comment by reversebias** [comment]
I agree. It seems like that link that I originally used keeps changing with new updates. Thanks for finding the static one.
